version: '3.8'

services:
  db-example-microservice:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: example-db-username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: example-db-name
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5401:5432"

networks:
  default:
    external: true
    name: aimcup-network